import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

import "./globals.css";

export const metadata: Metadata = {
	title: "ChatPDF",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider afterSignOutUrl="/">
			<html lang="en">
				<body>
					{children}

					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
